package eus.klimu.notification.api;

import eus.klimu.location.domain.model.Location;
import eus.klimu.location.domain.model.LocationDTO;
import eus.klimu.location.domain.service.definition.LocationService;
import eus.klimu.notification.domain.model.*;
import eus.klimu.notification.domain.service.definition.NotificationService;
import eus.klimu.notification.domain.service.definition.NotificationTypeService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Create, update, delete and get information for the Notifications. They represent the different notifications
 * generated by the KLIMU alert system. Takes care of all the CRUD methods, working with the database through an
 * internal Service.
 */
@Controller
@RequestMapping("/notification")
@RequiredArgsConstructor
public class NotificationController {

    /**
     * A class that allows modifying the notification types.
     */
    private final NotificationTypeService notificationTypeService;
    /**
     * A class that allows modifying the notifications.
     */
    private final NotificationService notificationService;
    /**
     * A class that allows modifying the locations.
     */
    private final LocationService locationService;

    /**
     * <p>Get a notification based on its ID.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/{id}">https://klimu.eus/RestAPI/notification/{id}</a></p>
     *
     * <ul>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param id The ID of the notification to look for.
     * @return A 200 ok if the notification was found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/{id}",
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
    )
    public ResponseEntity<Notification> getNotification(@PathVariable long id) {
        if (id > 0) {
            return ResponseEntity.ok().body(notificationService.getNotificationById(id));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get a list of notifications based on a location.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/location">https://klimu.eus/RestAPI/notification/location</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param location The location of the notification to look for.
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/location",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotifications(@RequestBody LocationDTO location) {
        if (location != null) {
            return ResponseEntity.ok().body(
                    notificationService.getAllNotifications(Location.generateLocation(location)));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get a list of notifications based on its type.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/type">https://klimu.eus/RestAPI/notification/type</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationType The type of the notification to look for.
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/type",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotifications(@RequestBody NotificationTypeDTO notificationType) {
        if (notificationType != null) {
            return ResponseEntity.ok().body(
                    notificationService.getAllNotifications(NotificationType.generateNotificationType(notificationType)));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get a list of notifications for a specific date and a location.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/date/location">https://klimu.eus/RestAPI/notification/date/location</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param location The location the notifications must be from.
     * @param startDate The date the notifications must be higher from.
     * @param endDate The date the notification must be lower from.
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/date/location",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotifications(
            @RequestBody LocationDTO location,
            @RequestBody Date startDate,
            @RequestBody Date endDate
    ) {
        DatePeriod datePeriod = null;

        if (startDate != null && endDate != null) {
            datePeriod = new DatePeriod(startDate, endDate);
        }
        if (location != null && datePeriod != null && datePeriod.check()) {
            return ResponseEntity.ok().body(notificationService.getNotificationsByDateBetween(
                    Location.generateLocation(location), datePeriod.getStartDate(), datePeriod.getEndDate()
            ));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get a list of notifications for a specific date and type.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/date/type">https://klimu.eus/RestAPI/notification/date/type</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationType The type the notifications must be from.
     * @param startDate The date the notifications must be higher from.
     * @param endDate The date the notification must be lower from.
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/date/type",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotifications(
            @RequestBody NotificationTypeDTO notificationType,
            @RequestBody Date startDate,
            @RequestBody Date endDate
    ) {
        DatePeriod datePeriod = null;

        if (startDate != null && endDate != null) {
            datePeriod = new DatePeriod(startDate, endDate);
        }
        if (notificationType != null && datePeriod != null && datePeriod.check()) {
            return ResponseEntity.ok().body(notificationService.getNotificationsByDateBetween(
                    NotificationType.generateNotificationType(notificationType),
                    datePeriod.getStartDate(), datePeriod.getEndDate()
            ));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get all the notifications stored on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/all">https://klimu.eus/RestAPI/notification/all</a></p>
     *
     * <ul>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/all",
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotifications() {
        return ResponseEntity.ok().body(notificationService.getAllNotifications());
    }

    /**
     * <p>Get the last 50 notifications stored on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/all/limited">https://klimu.eus/RestAPI/notification/all/limited</a></p>
     *
     * <ul>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @return A 200 ok if the notifications were found or a 400 bad request if it wasn't.
     */
    @GetMapping(
            value = "/all/limited",
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> getNotificationsLimited() {
        return ResponseEntity.ok().body(notificationService.getAllNotificationsLimited());
    }

    /**
     * <p>Save a new Notification on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/create">https://klimu.eus/RestAPI/notification/create</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notification The notification that is going to be stored.
     * @return A 200 ok if the notification was created or a 400 bad request if it wasn't.
     */
    @PostMapping(
            value = "/create",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
    )
    public ResponseEntity<Notification> createNotification(@RequestBody NotificationDTO notification) {
        if (notification != null) {
            return ResponseEntity.created(
                    URI.create(ServletUriComponentsBuilder.fromCurrentContextPath().path("/notification/create").toUriString())
            ).body(notificationService.addNewNotification(Notification.generateNotification(
                    notification, notificationTypeService, locationService
            )));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Save an X amount of notifications on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/create/all">https://klimu.eus/RestAPI/notification/create/all</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json</li>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notifications The notification that is going to be stored.
     * @return A 200 ok if the notifications were created or a 400 bad request if it wasn't.
     */
    @PostMapping(
            value = "/create/all",
            consumes = {MediaType.APPLICATION_JSON_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<Notification>> createAllNotifications(@RequestBody List<NotificationDTO> notifications) {
        if (notifications != null && !notifications.isEmpty()) {
            List<Notification> persistentNotifications = new ArrayList<>();
            notifications.forEach(n -> persistentNotifications.add(Notification.generateNotification(
                    n, notificationTypeService, locationService
            )));

            return ResponseEntity.created(
                    URI.create(ServletUriComponentsBuilder.fromCurrentContextPath().path("/notification/create/all").toUriString())
            ).body(notificationService.addAllNotifications(persistentNotifications));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Update a notification on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/update">https://klimu.eus/RestAPI/notification/update</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notification The notification that is going to be stored.
     * @return A 200 ok if the notification was updated or a 400 bad request if it wasn't.
     */
    @PutMapping(
            value = "/update",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
    )
    public ResponseEntity<Notification> updateNotification(@RequestBody NotificationDTO notification) {
        if (notification != null && notificationService.getNotificationById(notification.getId()) != null) {
            return ResponseEntity.ok().body(notificationService.updateNotification(Notification.generateNotification(
                    notification, notificationTypeService, locationService
            )));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Delete a notification by its ID.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/delete/{id}">https://klimu.eus/RestAPI/notification/delete/{id}</a></p>
     *
     * <ul>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param id The ID of the notification that is going to be deleted.
     * @return A 200 ok if the notification was deleted or a 400 bad request if it wasn't.
     */
    @DeleteMapping(value = "/delete/{id}")
    public ResponseEntity<Object> deleteNotification(@PathVariable long id) {
        if (id > 0) {
            notificationService.deleteNotification(notificationService.getNotificationById(id));
            return ResponseEntity.ok().build();
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Delete a notification from the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification/delete">https://klimu.eus/RestAPI/notification/delete</a></p>
     *
     * <ul>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notification The notification that is going to be deleted.
     * @return A 200 ok if the notification was deleted or a 400 bad request if it wasn't.
     */
    @DeleteMapping(value = "/delete", consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
    public ResponseEntity<Object> deleteNotification(@RequestBody NotificationDTO notification) {
        if (notification != null && notificationService.getNotificationById(notification.getId()) != null) {
            notificationService.deleteNotification(Notification.generateNotification(
                    notification, notificationTypeService, locationService
            ));
            return ResponseEntity.ok().build();
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }
}
