package eus.klimu.notification.api;

import eus.klimu.notification.domain.model.NotificationType;
import eus.klimu.notification.domain.model.NotificationTypeDTO;
import eus.klimu.notification.domain.service.definition.NotificationTypeService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;

/**
 * Create, update, delete and get information for the Notification Types. They represent the different notifications
 * that can be generated. Takes care of all the CRUD methods, working with the database through an internal Service.
 */
@Controller
@RequestMapping("/notification-type")
@RequiredArgsConstructor
public class NotificationTypeController {

    /**
     * A class that allows modifying the notification types.
     */
    private final NotificationTypeService notificationTypeService;

    /**
     * <p>Get a notification type based on its ID.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/{id}">https://klimu.eus/RestAPI/notification-type/{id}</a></p>
     *
     * <ul>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param id The ID of the notification type to look for.
     * @return A 200 ok if the notification type was found or a 400 bad request if it wasn't.
     */
    @GetMapping(value = "/{id}", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
    public ResponseEntity<NotificationType> getNotificationType(@PathVariable long id) {
        if (id > 0) {
            return ResponseEntity.ok().body(notificationTypeService.getNotificationType(id));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get a notification type based on its name.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/name/{name}">https://klimu.eus/RestAPI/notification-type/name/{name}</a></p>
     *
     * <ul>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param name The name of the notification type to look for.
     * @return A 200 ok if the notification type was found or a 400 bad request if it wasn't.
     */
    @GetMapping(value = "/name/{name}", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
    public ResponseEntity<NotificationType> getNotificationTypeByName(@PathVariable String name) {
        if (name != null) {
            return ResponseEntity.ok().body(notificationTypeService.getNotificationType(name));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Get all the notification types from the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/all">https://klimu.eus/RestAPI/notification-type/all</a></p>
     *
     * <ul>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @return A 200 ok if the notification types were found or a 400 bad request if it wasn't.
     */
    @GetMapping(value = "/all", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<List<NotificationType>> getNotifications() {
        return ResponseEntity.ok().body(notificationTypeService.getAllNotificationTypes());
    }

    /**
     * <p>Get all the notification types of an specific type (Dangerous, Warning or Information).</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/all/{type}">https://klimu.eus/RestAPI/notification-type/all/{type}</a></p>
     *
     * <ul>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param type The notification type to filter with.
     * @return A 200 ok if the notification types were found or a 400 bad request if it wasn't.
     */
    @GetMapping(value = "/all/{type}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<List<NotificationType>> getNotifications(@PathVariable String type) {
        if (type != null) {
            return ResponseEntity.ok().body(notificationTypeService.getAllNotificationTypes(type));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Save a new notification type on the database. Once it's saved, it is returned with the ID generated by the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/create">https://klimu.eus/RestAPI/notification-type/create</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationType The notification type that is going to be saved.
     * @return A 200 ok if the notification type was created or a 400 bad request if it wasn't.
     */
    @PostMapping(
            value = "/create",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
    )
    public ResponseEntity<NotificationType> createNotificationType(@RequestBody NotificationTypeDTO notificationType) {
        if (notificationType != null) {
            return ResponseEntity.created(
                    URI.create(ServletUriComponentsBuilder.fromCurrentContextPath()
                            .path("/notification-type/create").toUriString())
            ).body(notificationTypeService.addNewNotificationType(NotificationType.generateNotificationType(notificationType)));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Save an X new amount of notification types on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/create/all">https://klimu.eus/RestAPI/notification-type/create/all</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json</li>
     *     <li>Produces: application/json</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationTypes The list of the notification type that are going to be saved.
     * @return A 200 ok if the notification types were created or a 400 bad request if it wasn't.
     */
    @PostMapping(
            value = "/create/all",
            consumes = {MediaType.APPLICATION_JSON_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public ResponseEntity<List<NotificationType>> createAllNotificationTypes(
            @RequestBody List<NotificationTypeDTO> notificationTypes)
    {
        if (notificationTypes != null && !notificationTypes.isEmpty()) {
            List<NotificationType> persistentNotificationTypes = new ArrayList<>();
            notificationTypes.forEach(n -> persistentNotificationTypes.add(NotificationType.generateNotificationType(n)));

            return ResponseEntity.created(
                    URI.create(ServletUriComponentsBuilder.fromCurrentContextPath().path("/notification/create/all").toUriString())
            ).body(notificationTypeService.addAllNotificationTypes(persistentNotificationTypes));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Update a notification type on the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/update">https://klimu.eus/RestAPI/notification-type/update</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationType The notification type that is going to be updated.
     * @return A 200 ok if the notification type was updated or a 400 bad request if it wasn't.
     */
    @PutMapping(
            value = "/update",
            consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
    )
    public ResponseEntity<NotificationType> updateNotificationType(@RequestBody NotificationTypeDTO notificationType) {
        if (notificationType != null && notificationTypeService.getNotificationType(notificationType.getId()) != null) {
            return ResponseEntity.ok().body(notificationTypeService.updateNotificationType(
                    NotificationType.generateNotificationType(notificationType)
            ));
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Delete a notification type based on its ID.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/delete/{id}">https://klimu.eus/RestAPI/notification-type/delete/{id}</a></p>
     *
     * <ul>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param id The ID of the notification type that is going to be deleted.
     * @return A 200 ok if the notification type was deleted or a 400 bad request if it wasn't.
     */
    @DeleteMapping(value = "/delete/{id}")
    public ResponseEntity<Object> deleteNotificationType(@PathVariable long id) {
        NotificationType notificationType = notificationTypeService.getNotificationType(id);

        if (id > 0 && notificationType != null) {
            notificationTypeService.deleteNotificationType(notificationType);
            return ResponseEntity.ok().build();
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * <p>Delete a notification type from the database.</p>
     *
     * <p><a href="https://klimu.eus/RestAPI/notification-type/delete">https://klimu.eus/RestAPI/notification-type/delete</a></p>
     *
     * <ul>
     *     <li>Consumes: application/json, application/xml</li>
     *     <li>Produces: application/json, application/xml</li>
     *     <li>Requires: Access and Refresh tokens as headers.</li>
     * </ul>
     *
     * @param notificationType The notification type that is going to be deleted.
     * @return A 200 ok if the notification type was deleted or a 400 bad request if it wasn't.
     */
    @DeleteMapping(value = "/delete", consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
    public ResponseEntity<Object> deleteNotificationType(@RequestBody NotificationTypeDTO notificationType) {
        if (notificationType != null && notificationTypeService.getNotificationType(notificationType.getId()) != null) {
            notificationTypeService.deleteNotificationType(NotificationType.generateNotificationType(notificationType));
            return ResponseEntity.ok().build();
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }
}
